services:
  zentra-product-service-postgres:
    container_name: zentra-product-service-postgres
    image: postgres:16.0
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: zentra-product-service-postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./doc/database/postgresql/postgresql.conf
        target: /etc/postgresql/postgresql.conf
    networks:
      - zentra-network
      - zentra-product-service-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    restart: on-failure

  zentra-product-service:
    image: zentra-product-service:latest
    container_name: zentra-product-service
    ports:
      - "3500:3500"
      - "4500:4500"
    networks:
      - zentra-network
      - zentra-product-service-network
    depends_on:
      - zentra-product-service-postgres
    environment:
      - ZENTRA_APP_STATUS=PRODUCTION
      - ZENTRA_CONFIG_ADDRESS=[vault_address]
      - ZENTRA_CONFIG_TOKEN=[vault_token]
    volumes:
      - ./workspace:/app/workspace
      - ./tmp:/app/workspace/tmp
      - zentra-product-service-logs:/app
    restart: on-failure

volumes:
  zentra-product-service-postgres-data:
    name: zentra-product-service-postgres-data
  zentra-product-service-logs:
    name: zentra-product-service-logs

networks:
  zentra-product-service-network:
    name: zentra-product-service-network
    driver: bridge
  zentra-network:
    name: zentra-network
    external: true
